name: Tests

on:
    workflow_dispatch:
    push:
    schedule:
        - cron: 0 0 * * 0

jobs:
    tests:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install tox
            - name: Run tox
              run: |
                  tox -e py
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
              with:
                  flags: unittests
                  verbose: true
